### ISSUE TITLE
Upgrade 3rd party for security patches

### ISSUE THREAD

**Issue by katjam** [neontribe/seap_core#97]

**Comment by zii-67** [comment]
found 126 vulnerabilities (35 low, 24 moderate, 67 high) in 14475 scanned packages
  run `npm audit fix` to fix 63 of them.
  48 vulnerabilities require semver-major dependency updates.
  15 vulnerabilities require manual review. See the full report for details.

**Comment by AlinChindea** [comment]
![Screenshot from 2019-10-08 15-01-52](https://user-images.githubusercontent.com/29477363/66412734-0496f100-e9ee-11e9-9e92-a7e571afc7d5.png)
