### ISSUE TITLE
JustGiving page missing

### ISSUE THREAD

**Issue by Hoolean** [neontribe/seap_core#98]
# Problem

The JustGiving page linked in the home page's call-to-action is missing.

**Comment by katjam** [comment]
https://www.justgiving.com/s-e-a-p

**Comment by jermyk** [comment]
- [ ] **Testing on** http://neontribe.github.io/seap_core/

 - [x]   User can navigate to the Just giving page by selecting the nav button on the 
 actual /seap_core/ page

https://www.justgiving.com/s-e-a-p

![Screenshot_110519_032343_PM](https://user-images.githubusercontent.com/4446325/68220787-419bd680-ffe0-11e9-805d-09d2cc604dd2.jpg)

![Screenshot_110519_032525_PM](https://user-images.githubusercontent.com/4446325/68220928-7e67cd80-ffe0-11e9-86f6-9c263fa3d8cd.jpg)


@AlinChindea 
If the user navs to either the Help preparing for ESA or Help preparing for PIP from http://neontribe.github.io/seap_core/ and THEN selects the respective DONATE button, the page still errors for both ESA and PIP. likewise the user doesn't see the red testing page banner for either site  along this route?

User did empty cache and hard reload for both routes and still witnessed errors. 
![Screenshot_110519_035755_PM](https://user-images.githubusercontent.com/4446325/68223623-08199a00-ffe5-11e9-8bde-863837816e8e.jpg)

**Comment by jermyk** [comment]
- [ ] **Testing on **http://neontribe.github.io/seap_esa/#main-menu**
 - [ ]   User can navigate to the Just giving page https://www.justgiving.com/s-e-a-p

![Screenshot_110519_033152_PM](https://user-images.githubusercontent.com/4446325/68221787-e4088980-ffe1-11e9-859f-485ae785af3e.jpg)

![Screenshot_110519_033552_PM](https://user-images.githubusercontent.com/4446325/68221831-f4206900-ffe1-11e9-9cc9-4a01ea6ae07f.jpg)

**Comment by jermyk** [comment]
@AlinChindea 

 - [ ] Why doesn't the http://neontribe.github.io/seap_core page have the red banner like the others?

**Comment by AlinChindea** [comment]
> ![Screenshot_110519_032525_PM](https://user-images.githubusercontent.com/4446325/68220928-7e67cd80-ffe0-11e9-86f6-9c263fa3d8cd.jpg)
> 
> @AlinChindea
> If the user navs to either the Help preparing for ESA or Help preparing for PIP from http://neontribe.github.io/seap_core/ and THEN selects the respective DONATE button, the page still errors for both ESA and PIP. likewise the user doesn't see the red testing page banner for either site along this route?
> 
> User did empty cache and hard reload for both routes and still witnessed errors.
> ![Screenshot_110519_035755_PM](https://user-images.githubusercontent.com/4446325/68223623-08199a00-ffe5-11e9-8bde-863837816e8e.jpg)

@jermyk that's because they navigate the user to the live pages of ESA and PIP respectively and not to the staging ones where we are testing the new URL. The live versions still have the broken links.

**Comment by AlinChindea** [comment]
> @AlinChindea
> 
> * [ ]  Why doesn't the http://neontribe.github.io/seap_core page have the red banner like the others?

I don't know. That decision precedes my arrival to neontribe. @katjam ? :point_up:

**Comment by jermyk** [comment]
@AlinChindea 

Thnanks for the explanation re user naving to the live version of the sites.

Happy to pass this ticket on that basis

@katjam fyi.
